---
# tasks file for k8s_slave


- name: "Installing dependency"
  shell: "yum install -y yum-utils"

- name: "Installing dependency"
  shell: "yum-config-manager  --add-repo  https://download.docker.com/linux/centos/docker-ce.repo"

- name: "Installing docker"
  shell: "yum install -y  docker-ce docker-ce-cli containerd.io"

- name: "Enabelling docker services"
  service:
    name: "docker"
    state: started
    enabled: yes

- name: "copying docker  file"
  copy:
    src:  "daemon.json"
    dest: "/etc/docker/daemon.json"

- name: "restarting docker services"
  service:
    name: "docker"
    state: restarted


- name: "Creating file"
  shell: "touch /etc/yum.repos.d/kubernetes.repo"

- name: "configuring kubernetes repo"
  blockinfile:
    path: "/etc/yum.repos.d/kubernetes.repo"
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: "Kubernetes Installation"
  shell: "yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"

- name: "Kubelet service starting"
  service:
    name: "kubelet"
    state: started
    enabled: yes

- name: "iproute-tc installation"
  package:
    name: "iproute-tc"
    state: present

- name: "copying docker  file"
  copy:
    src:  "k8s.conf"
    dest: "/etc/sysctl.d/k8s.conf"

    
- name: "starting system service"
  shell: "sysctl --system"

- name: "Editing internal file"
  shell: "echo 1 > /proc/sys/net/ipv4/ip_forward"
  
- name: "Token Copy..."
  copy:
   src: "token.txt"
   dest: "/root/token.txt"

- name: "Join..."
  shell:
   cmd: "bash /root/token.txt"
  ignore_errors: yes
