---
# tasks file for k8s_master


- name: "Installing docker"
  package:
    name: "docker"
    state: present 

- name: "Enabelling docker services"
  service:
    name: "docker"
    state: started
    enabled: yes

- name: "creating file"
  shell: "touch /etc/yum.repos.d/kubernetes.repo"   
    
- name: "configuring kubernetes repo"
  blockinfile:
    path: "/etc/yum.repos.d/kubernetes.repo"
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: "copying docker  file"
  copy:
    src:  "daemon.json"
    dest: "/etc/docker/daemon.json"

- name: "restarting docker services"
  service:
    name: "docker"
    state: restarted


- name: "Kubernetes Installation"
  package:
    name: "kubelet"
    state: present

- name: "Kubernetes Installation"
  package:
    name: "kubeadm"
    state: present

- name: "Kubernetes Installation"
  package:
    name: "kubectl"
    state: present


- name: "iproute-tc installation"
  package:
    name: "iproute-tc"
    state: present

- name: "copying docker  file"
  copy:
    src:  "k8s.conf"
    dest: "/etc/sysctl.d/k8s.conf"

    
- name: "starting system service"
  shell: "sysctl --system"

- name: "Kubelet sevcie starting"
  service:
    name: "kubelet"
    state: started
    enabled: yes

- name: "Pulling kubernetes images"
  shell: "kubeadm config images pull"

- name: "Kubernet service initialization"
  shell: "kubeadm init --pod-network-cidr=10.240.0.0/16  --control-plane-endpoint={{ ip }}:6443  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  ignore_errors: yes

- name: "making folder"
  shell: " mkdir -p $HOME/.kube"

- name: "Duplicate Folder Deletion..."
  file:
    path: "$HOME/.kube/config"
    state: absent
  ignore_errors: yes 

- name: "copying conf file"
  shell: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

- name: "changing owner"
  shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: "Flannel starting"
  shell: " kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

- name: "creating tokken"
  shell: "kubeadm token create  --print-join-command"
  register: token

- name: "Token save to gcp"
  local_action:
         copy
             content="{{ token.stdout }}"
             dest="/gcp_dynamic/token.txt"

- name: "Token save to azure"
  local_action:
         copy
             content="{{ token.stdout }}"
             dest="/azure_dynamic/token.txt"
